module.exports = constant = {
  DEV: "development",
  TOO_MANY_REQUEST_MSG: "Too many requests, please try again after 20 minutes.",
  NOT_FOUND_MSG: "Not Found",
  DISPLAY_MSG: "Displayed Successfully",
  SERVER_ERR: "Internal server error",
  STATUS_ACTIVE: "active",
  STATUS_INACTIVE: "Inactive",
  STATUS_WARNING: "warning",
  STATUS_ERROR: "error",
  STATUS_SUCCESS: "success",
  STATUS_DRAFT: "Draft",
  STATUS_OVERDUE: "Overdue",
  STATUS_COMPLETE: "Complete",
  STATUS_INVOICE_RAISED: "Invoice raised",
  STATUS_SUBMITTED: "Submitted",
  STATUS_WITHDRAW_PENDING: "withdrawal pending",
  STATUS_WITHDRAW_APPROVE: "withdrawal approved",
  STATUS_WITHDRAW_REJECT: "withdrawal rejected",
  STATUS_APPROVED: "approved",
  STATUS_REJECTED: "rejected",
  STATUS_FAIL: "fail",
  STATUS_OTHERS: "Others",
  STATUS_PENDING: "pending",
  STATUS_ACCEPTED: "accepted",
  DATA_UPDATE_SUCCESS_MSG: "data updated successfully",
  INVALID_UPDATE_DATA_MSG: "Invalid update data",
  FIELD_YOE: "yearsOfExperience",
  FIELD_REMAIN_ALLOCATION: "remainingAllocation",
  DESIGNATION_MANAGER: "Manager",
  ACTIVE_CLIENT: "Active Client",
  INACTIVE_CLIENT: "Inactive Client",
  DATA_FETCH_MSG: "Data fetched successfully",
  INVALID_REQ_DATA_MSG: "Invalid request data",
  SUCESS_MSG: "success",
  NO_DATA_FOUND_MSG: "no data found!",
  DROPDOWN_NOT_FOUND_MSG: "dropdown not found (No Content)",
  DROPDOWN_NOT_FOUND_BY_ID_MSG: "dropdown not found by given id",
  GET_DROPDOWN_SUCCESS_MSG: "getDropdownComplete success",
  CREATE_SUCCESS_MSG: "create success",
  UPDATE_DROPDOWN_FAIL_MSG: "Update dropdown by id failed",
  UPDATE_SUCCESS_MSG: "update succcess",
  REMOVE_DROPDOWN_FAIL_MSG: "Remove dropdown by id failed",
  DELETE_DROPDOWN_FAIL_MSG: "dropdown delete by id has failed",
  DELETE_DROPDOWN_SUCCESS_MSG: "dropdown successfully deleted",
  ACTIVE_STATUS_CHANGE_FAIL_MSG: "Active Status Change Failed",
  ACTIVE_STATUS_CHANGE_SUCCESS_MSG: "Active Status changed",
  ACTIVE_CHANGE_ERROR_MSG: "Error changing active",
  INVALID_OBJ_ID_MSG: "Invalid objectId id",
  EMPLOYEE_NOT_FOUND_MSG: "Employee not found by given id",
  UPDATE_EMPLOYEE_FAIL_MSG: "Update employee by id failed",
  EMPLOYEE_DEL_FAIL_MSG: "Employee delete by id has failed",
  EMPLOYEE_DEL_SUCCESS_MSG: "Employee successfully deleted",
  INVALID_DATA_MSG: "Invalid Data",
  INADEQUATE_DATA_MSG: "Inadequate Data (Check error list)",
  NO_REWARDS_FOUND_MSG: "Bad Request, No rewards found",
  SUCCESS_WITH_ERR_MSG: "success with Error (Check error list)",
  FAILED_TO_IMPORT_MSG: "Failed to import (Check error list)",
  IMPORT_SUCCESS_MSG: "Imported Data successfully",
  JOI_ERROR: "joi-error",
  MONGO_ERROR: "mongo-error",
  UPLOAD_PROFILE_PIC_SUCCESS_MSG: "Successfully uploaded profile picture",
  DEL_PROFILE_PIC_SUCCESS_MSG: "Successfully deleted profile picture",
  FALLBACK_FETCH_SUCCESS_MSG: "Fall back time fetched successfully",
  FALLBACK_UPDATE_SUCCESS_MSG: "Updated fallback time successfully",
  FALLBACK_UPDATE_FAIL_MSG: "Updating fall back time failed",
  FALLBACK_ADD_SUCCESS_MSG: "Added fallBackModel successfully",
  INVALID_REQUEST_MSG:
    "Invalid request. Please provide module name in query params",
  QA_ADD_SUCCESS_MSG: "QnA successfully added",
  SOMETHING_WRONG_MSG: "Something went wrong",
  LEAVES_FETCH_SUCCESS_MSG: "all leaves fetched successfully",
  HOLIDAY_CREATE_SUCCESS_MSG: "Holiday created Successfully",
  HOLIDAY_DISABLE_SUCCESS_MSG: "Disable holiday Successfully",
  HOLIDAY_ENABLE_SUCCESS_MSG: "Enable holiday Successfully",
  CURRENCY_INR: "INR",
  CURRENCY_RS: "Rs.",
  CURRENCY_DOLLER: "$",
  PURCHASE_ORDERS: "purchase_orders",
  PO_ID: "poId",
  INVOICE_AMOUNT_RECEIVED: "invoice_amount_received",
  LOCALE: "en",
  EMPID_INVALID_REQ_MSG:
    "Invalid request. Please provide empID in query params",
  LEAVE_APPLIED_SUCCESS_MSG: "Leave applied successfully",
  INSUFFICIENT_LEAVES_MSG: "Insufficient leave balance",
  LEAVES_FETCH_SUCCESS_MSG: "all leaves fetched successfully",
  LEAVE_RECORD_FETCH_SUCCESS_MSG: "Leave records fetched successfully",
  STATUS_CHANGE_SUCCESS_MSG: "status changed successfully",
  PROJ_ID_INVALID_REQ_MSG:
    "Invalid request. Please provide project id in query params",
  FILE_UPLOAD_SUCCESS_MSG: "file successfully uploaded.",
  MONGO_SERVER_ERR: "MongoServerError",
  TYPE_EXIST_MSG: "Type already exist!",
  TYPE_NOT_FOUND_MSG: "Type not found!",
  TYPE_DEL_SUCCESS_MSG: "Type deleted successfully",
  DUMMY_USERNAME: "Dummy username",
  TOKEN_EXPIRES_IN: "3600s",
  PINCODE_NOT_EXIST_MSG: "The pincode doesnt exist",
  NO_RECORD_FOUND_MSG: "No record with this id found",
  DATA_WITH_BRAND_EXIST_MSG: "Data with this brand name already exists",
  DATA_UNIQUE_MSG: "Data is unique",
  DATA_WITH_LEGAL_NAME_MSG: "Data with this legal name already exists",
  INVALID_REQ_QUERY_MSG: "Invalid request Query",
  CLIENT_INFO_UPDATE_SUCCESS_MSG:
    "client info updated on all project successfully",
  REVIEW_NOT_FOUND_MSG: "review not found by given id",
  EMPLOYEE_CREATED_MSG: "Employee created",
  EMPLOYEE_UPDATED_MSG: "Employee updated",
  USERS_DATA_CREATED_SUCCESS_MSG: "Created Users Data successfully",
  FAILED_CREATE_USERS_DATA_MSG:
    "Failed to create User  (Check Created-User error list)",
  FEW_USERS_DATA_NOT_CREATED_MSG:
    "success with Error, few users account failed to create (Check Created-User error list)",
  USER_UPDATED_SUCCESS_MSG: "user successfully updated!",
  USER_DELETED_SUCCESS_MSG: "user successfully deleted!",
  USER_DEACTIVATED_MSG: "user is Deactivated",
  TOKEN_VALID_MSG: "Valid Token",
  TOKEN_INVALID_MSG: "Invalid Token",
  AUTHENTICATION_ERR_MSG: "Authentication error. Token required.",
  ENV_TEST: "test",
  TEST_EMAIL: "test@gmail.com",
  USER_LOGOUT_MSG: "User successfully Logout",
  BAD_REQ_MSG: "Bad Request",
  USER_NOT_FOUND_WITH_EMAIL_MSG: "User not found with this email",
  EMAIL_RESET_PASSWORD_MSG: "email sent for password reset",
  USER_INACTIVE_OR_DELETED_MSG: "User inactive or deleted",
  //weekdays
  WEEK_CREATED_MSG: "Week created successfully!",
  WEEK_EXIST_MSG: "week already exist!",
  WEEK_FETCHED_MSG: "Week Fetched successfully!",
  WEEK_UPDATED_MSG: "Week updated successfully!",
  WEEK_DELETED_MSG: "Week deleted successfully!",
  //Allocations
  GET_ALLOCATION_SUCCESS: "Fetched allocations successfully",
  GET_ALLOCATION_BENCH_SUCCESS: "Fetched allocations on bench successfully",
  GET_ALLOCATION_EMPID_SUCCESS: "Successfully fetched allocation of employee",
  GET_FILTERED_EMPLOYEES_SUCCESS: "Filtered employees successfully",
  GET_MANAGERS_SUCCESS: "Fetched managers successfully",
  CREATE_ALLOCATION_SUCCESS: "Allocation added successfully",
  UPDATE_ALLOCATION_SUCCESS: "Updated allocation successfully",
  UPDATE_RESOURCE_SUCCESS: "Updated resource successfully",
  DELETE_RESOURCE_SUCCESS: "Deleted resource successfully",
  UPDATE_PROJECT_DESCRIPTION_SUCCESS:
    "Updated project description successfully",
  // PROJECTS
  UPDATE_PROJECT_SUCCESS: "Updated project successfully",
  GET_PROJECT_ID_SUCCESS: "Fetched project by id successfully",
  //Clients
  GET_FILTERED_CLIENTS_SUCCESS: "Filtered clients successfully",
  GET_CLIENT_ID_SUCCESS: "Fetched client by Id successfully",
  //utility
  ENV_PRODUCTION: "production",
  EMAIL_FROM: "Oneplace <oneplace@valuebound.com>",
  STATUS_FAILURE: "failure",
  //middleware
  USER_NOT_EXIST_MSG: "User with the given credentials doesn't exists!",
  NOT_AUUTH_FOR_ROUTE_MSG: "Not Authorized for this route",
  NOT_LOGGED_IN_MSG: "You are not logged in please login to get access",
  EMP_TOKEN_ERR_MSG: "The employee with this token no longer exist!!",
  NO_PERMISSION_ERR_MSG: "You do not have permission to perform this action",
  //HTTP Status codes
  HTTP_200_CODE: 200,
  HTTP_201_CODE: 201,
  HTTP_204_CODE: 204,
  HTTP_401_CODE: 401,
  HTTP_404_CODE: 404,
  HTTP_422_CODE: 422,
  HTTP_400_CODE: 400,
  HTTP_206_CODE: 206,
};
